### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by josevalim** [elixir-telemetry/telemetry#3]
Proposal:

> Telemetry is a dynamic dispatching library for metrics and instrumentations. It is lightweight, small and can be used in any Elixir project.
>
> In a nutshell, you register a custom module and function to be invoked for certain events, which are executed whenever there is such event. Event names are a list of atoms. Each event is composed of a numeric value and can have metadata attached to it. Let's see an example:
>
> ...

**Comment by arkgil** [comment]
> "Telemetry is a dynamic dispatching library for metrics and instrumentations. It is lightweight, small and can be used in any Elixir project."

Love it! I think we should add something along these lines to the `@moduledoc` of Telemetry module.
