### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by arkgil** [elixir-telemetry/telemetry#4]
Since the project is now public, I think it would be nice to have some CI set up to run tests on each PR. I see that Phoenix itself is using TravisCI, should we use it for this project as well?

/cc @josevalim @chrismccord

**Comment by josevalim** [comment]
Yes, let's go with travis. I have already enabled it on the travis side. So we just need a .travis.yml file.

**Comment by arkgil** [comment]
Great, thanks! I'll handle the config file.
